use crate::types::EventType;
use norm_sys::*;

/// A NORM event
///
/// This struct represents an event from the NORM protocol. It wraps the raw
/// C event struct and provides accessors for the event data.
///
/// Events are generated by the NORM protocol and can be retrieved using
/// `Instance::next_event` or `Instance::events`.
#[derive(Debug, Clone)]
pub struct Event {
    /// The type of event
    pub event_type: EventType,
    /// The session handle
    pub session: NormSessionHandle,
    /// The sender handle
    pub sender: NormNodeHandle,
    /// The object handle
    pub object: NormObjectHandle,
}

impl Event {
    /// Create a new event from a raw NORM event
    ///
    /// # Arguments
    /// * `raw_event` - The raw NORM event from the C API
    ///
    /// # Returns
    /// A new event struct
    pub(crate) fn from_raw(raw_event: NormEvent) -> Self {
        Event {
            event_type: EventType::from(raw_event.type_),
            session: raw_event.session,
            sender: raw_event.sender,
            object: raw_event.object,
        }
    }

    /// Check if this event is a specific event type
    ///
    /// # Arguments
    /// * `event_type` - The event type to check for
    ///
    /// # Returns
    /// `true` if the event is of the specified type, `false` otherwise
    pub fn is(&self, event_type: EventType) -> bool {
        self.event_type == event_type
    }
}

// This will be expanded later to provide additional helper methods and convenience functions
// for working with different event types