/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mil_navy_nrl_norm_NormEvent */

#ifndef _Included_mil_navy_nrl_norm_NormEvent
#define _Included_mil_navy_nrl_norm_NormEvent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mil_navy_nrl_norm_NormEvent
 * Method:    getObject
 * Signature: ()Lmil/navy/nrl/norm/NormObject;
 */
JNIEXPORT jobject JNICALL Java_mil_navy_nrl_norm_NormEvent_getObject
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
