/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mil_navy_nrl_norm_NormData */

#ifndef _Included_mil_navy_nrl_norm_NormData
#define _Included_mil_navy_nrl_norm_NormData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mil_navy_nrl_norm_NormData
 * Method:    getData
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_mil_navy_nrl_norm_NormData_getData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
