/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mil_navy_nrl_norm_NormInstance */

#ifndef _Included_mil_navy_nrl_norm_NormInstance
#define _Included_mil_navy_nrl_norm_NormInstance
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mil_navy_nrl_norm_NormInstance
 * Method:    createInstance
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_mil_navy_nrl_norm_NormInstance_createInstance
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     mil_navy_nrl_norm_NormInstance
 * Method:    destroyInstance
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mil_navy_nrl_norm_NormInstance_destroyInstance
  (JNIEnv *, jobject);

/*
 * Class:     mil_navy_nrl_norm_NormInstance
 * Method:    stopInstance
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mil_navy_nrl_norm_NormInstance_stopInstance
  (JNIEnv *, jobject);

/*
 * Class:     mil_navy_nrl_norm_NormInstance
 * Method:    restartInstance
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_mil_navy_nrl_norm_NormInstance_restartInstance
  (JNIEnv *, jobject);

/*
 * Class:     mil_navy_nrl_norm_NormInstance
 * Method:    suspendInstance
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_mil_navy_nrl_norm_NormInstance_suspendInstance
  (JNIEnv *, jobject);

/*
 * Class:     mil_navy_nrl_norm_NormInstance
 * Method:    resumeInstance
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mil_navy_nrl_norm_NormInstance_resumeInstance
  (JNIEnv *, jobject);

/*
 * Class:     mil_navy_nrl_norm_NormInstance
 * Method:    setCacheDirectory
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mil_navy_nrl_norm_NormInstance_setCacheDirectory
  (JNIEnv *, jobject, jstring);

/*
 * Class:     mil_navy_nrl_norm_NormInstance
 * Method:    openDebugLog
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mil_navy_nrl_norm_NormInstance_openDebugLog
  (JNIEnv *, jobject, jstring);

/*
 * Class:     mil_navy_nrl_norm_NormInstance
 * Method:    closeDebugLog
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mil_navy_nrl_norm_NormInstance_closeDebugLog
  (JNIEnv *, jobject);

/*
 * Class:     mil_navy_nrl_norm_NormInstance
 * Method:    openDebugPipe
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mil_navy_nrl_norm_NormInstance_openDebugPipe
  (JNIEnv *, jobject, jstring);

/*
 * Class:     mil_navy_nrl_norm_NormInstance
 * Method:    setDebugLevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_mil_navy_nrl_norm_NormInstance_setDebugLevel
  (JNIEnv *, jobject, jint);

/*
 * Class:     mil_navy_nrl_norm_NormInstance
 * Method:    getDebugLevel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_mil_navy_nrl_norm_NormInstance_getDebugLevel
  (JNIEnv *, jobject);

/*
 * Class:     mil_navy_nrl_norm_NormInstance
 * Method:    hasNextEvent
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_mil_navy_nrl_norm_NormInstance_hasNextEvent
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     mil_navy_nrl_norm_NormInstance
 * Method:    getNextEvent
 * Signature: ()Lmil/navy/nrl/norm/NormEvent;
 */
JNIEXPORT jobject JNICALL Java_mil_navy_nrl_norm_NormInstance_getNextEvent
  (JNIEnv *, jobject);

/*
 * Class:     mil_navy_nrl_norm_NormInstance
 * Method:    createSession
 * Signature: (Ljava/lang/String;IJ)Lmil/navy/nrl/norm/NormSession;
 */
JNIEXPORT jobject JNICALL Java_mil_navy_nrl_norm_NormInstance_createSession
  (JNIEnv *, jobject, jstring, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
