/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mil_navy_nrl_norm_NormFile */

#ifndef _Included_mil_navy_nrl_norm_NormFile
#define _Included_mil_navy_nrl_norm_NormFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mil_navy_nrl_norm_NormFile
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mil_navy_nrl_norm_NormFile_getName
  (JNIEnv *, jobject);

/*
 * Class:     mil_navy_nrl_norm_NormFile
 * Method:    rename
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mil_navy_nrl_norm_NormFile_rename
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
