/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mil_navy_nrl_norm_NormObject */

#ifndef _Included_mil_navy_nrl_norm_NormObject
#define _Included_mil_navy_nrl_norm_NormObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mil_navy_nrl_norm_NormObject
 * Method:    setNackingMode
 * Signature: (Lmil/navy/nrl/norm/enums/NormNackingMode;)V
 */
JNIEXPORT void JNICALL Java_mil_navy_nrl_norm_NormObject_setNackingMode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     mil_navy_nrl_norm_NormObject
 * Method:    getType
 * Signature: ()Lmil/navy/nrl/norm/enums/NormObjectType;
 */
JNIEXPORT jobject JNICALL Java_mil_navy_nrl_norm_NormObject_getType
  (JNIEnv *, jobject);

/*
 * Class:     mil_navy_nrl_norm_NormObject
 * Method:    getInfo
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_mil_navy_nrl_norm_NormObject_getInfo
  (JNIEnv *, jobject);

/*
 * Class:     mil_navy_nrl_norm_NormObject
 * Method:    getSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_mil_navy_nrl_norm_NormObject_getSize
  (JNIEnv *, jobject);

/*
 * Class:     mil_navy_nrl_norm_NormObject
 * Method:    getBytesPending
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_mil_navy_nrl_norm_NormObject_getBytesPending
  (JNIEnv *, jobject);

/*
 * Class:     mil_navy_nrl_norm_NormObject
 * Method:    cancel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mil_navy_nrl_norm_NormObject_cancel
  (JNIEnv *, jobject);

/*
 * Class:     mil_navy_nrl_norm_NormObject
 * Method:    retain
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mil_navy_nrl_norm_NormObject_retain
  (JNIEnv *, jobject);

/*
 * Class:     mil_navy_nrl_norm_NormObject
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mil_navy_nrl_norm_NormObject_release
  (JNIEnv *, jobject);

/*
 * Class:     mil_navy_nrl_norm_NormObject
 * Method:    getSender
 * Signature: ()Lmil/navy/nrl/norm/NormNode;
 */
JNIEXPORT jobject JNICALL Java_mil_navy_nrl_norm_NormObject_getSender
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
