@startuml
class NormFile {
    + <<const>> FILENAME_MAX : int = 260
    <<internal>> NormFile(handle:long)
    + Name : string <<get>>
    + Rename(filePath:string) : void
}
NormObject <|-- NormFile
@enduml
