@startuml
class NormObject {
    + <<const>> NORM_OBJECT_INVALID : int = 0
    # _handle : long
    <<internal>> NormObject(handle:long)
    + Handle : long <<get>>
    + Info : byte[] <<get>>
    + Size : long <<get>>
    + Sender : long <<get>>
    + SetNackingMode(nackingMode:NormNackingMode) : void
    + GetBytesPending() : long
    + Cancel() : void
    + Retain() : void
    + Release() : void
    + <<override>> GetHashCode() : int
    + <<override>> Equals(obj:object?) : bool
}
NormObject --> "Type" NormObjectType
@enduml
