@startuml
class NormNode {
    + <<const>> NORM_NODE_ANY : long = 0xffffffff
    + <<const>> NORM_NODE_NONE : int = 0
    + <<const>> NORM_NODE_INVALID : int = 0
    - _handle : long
    <<internal>> NormNode(handle:long)
    + Id : long <<get>>
    + Grtt : double <<get>>
    + GetCommand(buffer:byte[], offset:int, length:int) : int
    + SetUnicastNack(state:bool) : void
    + SetNackingMode(nackingMode:NormNackingMode) : void
    + SetRepairBoundary(repairBoundary:NormRepairBoundary) : void
    + SetRxRobustFactor(robustFactor:int) : void
    + FreeBuffers() : void
    + Retain() : void
    + Release() : void
}
NormNode --> "Address" IPEndPoint
@enduml
