@startuml 
struct NormEvent 
{
    + Type : NormEventType
    + Session : long
    + Sender : long
    + Object : long
}
class NormApi
{
    + <<const>> NORM_LIBRARY : string = "norm"
    + {static} NormCreateInstance(priorityBoost:bool) : long
    + {static} NormDestroyInstance(instanceHandle:long) : void
    + {static} NormStopInstance(instanceHandle:long) : void
    + {static} NormRestartInstance(instanceHandle:long) : bool
    + {static} NormSuspendInstance(instanceHandle:long) : bool
    + {static} NormResumeInstance(instanceHandle:long) : void
    + {static} NormSetCacheDirectory(instanceHandle:long, cachePath:string) : bool
    + {static} NormGetNextEvent(instanceHandle:long, theEvent:NormEvent, waitForEvent:bool) : bool 
    + {static} NormGetDescriptor(instanceHandle:long) : int 
    + {static} NormCreateSession(instanceHandle:long, sessionAddress:string, sessionPort:int, localNodeId:long) : long 
    + {static} NormDestroySession(sessionHandle:long) : void 
    + {static} NormGetLocalNodeId(sessionHandle:long) : long
    + {static} NormSetTxPort(sessionHandle:long, txPortNumber:int, enableReuse:bool, txBindAddress:string) : bool 
    + {static} NormSetTxOnly(sessionHandle:long, txOnly:bool, connectToSessionAddress:bool) : void 
    + {static} NormSetRxPortReuse(sessionHandle:long, enableReuse:bool, rxBindAddress:string, senderAddress:string, senderPort:int) : void 
    + {static} NormSetEcnSupport(sessionHandle:long, ecnEnable:bool, ignoreLoss:bool, tolerateLoss:bool) : void 
    + {static} NormSetMulticastInterface(sessionHandle:long, interfaceName:string) : bool 
    + {static} NormSetSSM(sessionHandle:long, sourceAddress:string) : bool 
    + {static} NormSetTTL(sessionHandle:long, ttl:byte) : bool 
    + {static} NormSetTOS(sessionHandle:long, tos:byte) : bool 
    + {static} NormSetLoopback(sessionHandle:long, loopback:bool) : bool
    + {static} NormSetMessageTrace(sessionHandle:long, state:bool) : void
    + {static} NormSetTxLoss(sessionHandle:long, precent:double) : void
    + {static} NormSetRxLoss(sessionHandle:long, precent:double) : void
    + {static} NormOpenDebugLog(instanceHandle:long, path:string) : bool 
    + {static} NormCloseDebugLog(instanceHandle:long) : void
    + {static} NormOpenDebugPipe(instanceHandle:long, pipeName:string) : bool 
    + {static} NormSetDebugLevel(level:int) : void 
    + {static} NormGetDebugLevel() : int
    + {static} NormSetReportInterval(sessionHandle:long, interval:double) : void
    + {static} NormGetRandomSessionId() : int 
    + {static} NormStartSender(sessionHandle:long, instanceId:int, bufferSpace:long, segmentSize:int, numData:short, numParity:short, fecId:NormFecType) : bool 
    + {static} NormStopSender(sessionHandle:long) : void
    + {static} NormSetTxRate(sessionHandle:long, bitsPerSecond:double) : void
    + {static} NormGetTxRate(sessionHandle:long) : double
    + {static} NormSetTxSocketBuffer(sessionHandle:long, bufferSize:long) : bool 
    + {static} NormSetFlowControl(sessionHandle:long, flowControlFactor:double) : void
    + {static} NormSetCongestionControl(sessionHandle:long, enable:bool, adjustRate:bool) : void 
    + {static} NormSetTxRateBounds(sessionHandle:long, rateMin:double, rateMax:double) : void
    + {static} NormSetTxCacheBounds(sessionHandle:long, sizeMax:long, countMin:long, countMax:long) : void 
    + {static} NormSetAutoParity(sessionHandle:long, autoParity:byte) : void 
    + {static} NormSetGrttEstimate(sessionHandle:long, grttEstimate:double) : void
    + {static} NormGetGrttEstimate(sessionHandle:long) : double
    + {static} NormSetGrttMax(sessionHandle:long, grttMax:double) : void
    + {static} NormSetGrttProbingMode(sessionHandle:long, probingMode:NormProbingMode) : void 
    + {static} NormSetGrttProbingInterval(sessionHandle:long, intervalMin:double, intervalMax:double) : void
    + {static} NormSetBackoffFactor(sessionHandle:long, backoffFactor:double) : void
    + {static} NormSetGroupSize(sessionHandle:long, groupSize:long) : void 
    + {static} NormSetTxRobustFactor(sessionHandle:long, robustFactor:int) : void
    + {static} NormFileEnqueue(sessionHandle:long, fileName:string, infoPtr:string, infoLen:int): long 
    + {static} NormDataEnqueue(sessionHandle:long, dataPtr:byte[], dataLen:int, infoPtr:byte[], infoLen:int) : long 
    + {static} NormRequeueObject(sessionHandle:long, objectHandle:long) : bool
    + {static} NormStreamOpen(sessionHandle:long, bufferSize:long, infoPtr:string, infoLen:int) : long 
    + {static} NormStreamClose(streamHandle:long, graceful:bool) : void 
    + {static} NormStreamWrite(streamHandle:long, buffer:byte[], numBytes:int) : int
    + {static} NormStreamFlush(streamHandle:long, eom:bool, flushMode:NormFlushMode) : void 
    + {static} NormStreamSetAutoFlush(streamHandle:long, flushMode: NormFlushMode) : void
    + {static} NormStreamSetPushEnable(streamHandle:long, pushEnable:bool) : void
    + {static} NormStreamHasVacancy(streamHandle:long) : bool
    + {static} NormStreamMarkEom(streamHandle:long) : void
    + {static} NormSetWatermark(sessionHandle:long, objectHandle:long, overrideFlush:bool) : bool
    + {static} NormResetWatermark(sessionHandle:long) : bool
    + {static} NormCancelWatermark(sessionHandle:long) : void
    + {static} NormAddAckingNode(sessionHandle:long, nodeId:long) : bool
    + {static} NormRemoveAckingNode(sessionHandle:long, nodeId:long) : void
    + {static} NormGetAckingStatus(sessionHandle:long, nodeId:long) : NormAckingStatus
    + {static} NormSendCommand(sessionHandle:long, cmdBuffer:byte[], cmdLength:int, robust:bool) : bool
    + {static} NormCancelCommand(sessionHandle:long) : void
    + {static} NormStartReceiver(sessionHandle:long, bufferSpace:long) : bool
    + {static} NormStopReceiver(sessionHandle:long) : void
    + {static} NormSetRxCacheLimit(sessionHandle:long, countMax:int) : void
    + {static} NormSetRxSocketBuffer(sessionHandle:long, bufferSize:long) : bool
    + {static} NormSetSilentReceiver(sessionHandle:long, silent:bool, maxDelay:int) : void
    + {static} NormSetDefaultUnicastNack(sessionHandle:long, unicastNacks:bool) : void
    + {static} NormNodeSetUnicastNack(remoteSender:long, unicastNacks:bool) : void
    + {static} NormSetDefaultSyncPolicy(sessionHandle:long, syncPolicy:NormSyncPolicy) : void
    + {static} NormSetDefaultNackingMode(sessionHandle:long, nackingMode:NormNackingMode) : void
    + {static} NormNodeSetNackingMode(remoteSender:long, nackingMode:NormNackingMode) : void
    + {static} NormObjectSetNackingMode(objectHandle:long, nackingMode:NormNackingMode) : void
    + {static} NormSetDefaultRepairBoundary(sessionHandle:long, repairBoundary:NormRepairBoundary) : void
    + {static} NormNodeSetRepairBoundary(remoteSender:long, repairBoundary:NormRepairBoundary) : void
    + {static} NormSetDefaultRxRobustFactor(sessionHandle:long, robustFactor:int) : void
    + {static} NormNodeSetRxRobustFactor(remoteSender:long, robustFactor:int) : void
    + {static} NormStreamRead(streamHandle:long, buffer:byte[], numBytes:int) : bool
    + {static} NormStreamSeekMsgStart(streamHandle:long) : bool
    + {static} NormStreamGetReadOffset(streamHandle:long) : long
    + {static} NormObjectGetType(objectHandle:long) : NormObjectType
    + {static} NormObjectHasInfo(objectHandle:long) : bool
    + {static} NormObjectGetInfoLength(objectHandle:long) : int
    + {static} NormObjectGetInfo(objectHandle:long, buffer:byte[], bufferLen:int) : int
    + {static} NormObjectGetSize(objectHandle:long) : int
    + {static} NormObjectGetBytesPending(objectHandle:long) : int
    + {static} NormObjectCancel(objectHandle:long) : void
    + {static} NormObjectRetain(objectHandle:long) : void
    + {static} NormObjectRelease(objectHandle:long) : void
    + {static} NormFileGetName(fileHandle:long, nameBuffer:string, bufferLen:int) : bool
    + {static} NormFileRename(fileHandle:long, fileName:string) : bool
    + {static} NormDataAccessData(objectHandle:long) : nint
    + {static} NormObjectGetSender(objectHandle:long) : long
    + {static} NormNodeGetId(nodeHandle:long) : long
    + {static} NormNodeGetAddress(nodeHandle:long, addrBuffer:byte[], bufferLen: int, port:int) : bool
    + {static} NormNodeGetGrtt(remoteSender:long) : double
    + {static} NormNodeGetCommand(remoteSender:long, buffer:byte[], buflen:int) : bool
    + {static} NormNodeFreeBuffers(remoteSender:long) : void
    + {static} NormNodeRetain(nodeHandle:long) : void
    + {static} NormNodeRelease(nodeHandle:long) : void
}
@enduml