name: .NET

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/dotnet

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Setup Python
      uses: actions/setup-python@v3.1.4
      with:
        python-version: 3.x
    - name: Build NORM
      run: ./waf
      working-directory: .
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore /property:Configuration=Release
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
